export const regions = [
  { code: '10', name: 'Blekinge län' },
  { code: '20', name: 'Dalarnas län' },
  { code: '09', name: 'Gotlands län' },
  { code: '21', name: 'Gävleborgs län' },
  { code: '13', name: 'Hallands län' },
  { code: '23', name: 'Jämtlands län' },
  { code: '06', name: 'Jönköpings län' },
  { code: '08', name: 'Kalmar län' },
  { code: '07', name: 'Kronobergs län' },
  { code: '25', name: 'Norrbottens län' },
  { code: '12', name: 'Skåne län' },
  { code: '01', name: 'Stockholms län' },
  { code: '04', name: 'Södermanlands län' },
  { code: '03', name: 'Uppsala län' },
  { code: '17', name: 'Värmlands län' },
  { code: '24', name: 'Västerbottens län' },
  { code: '22', name: 'Västernorrlands län' },
  { code: '19', name: 'Västmanlands län' },
  { code: '14', name: 'Västra Götalands län' },
  { code: '18', name: 'Örebro län' },
  { code: '05', name: 'Östergötlands län' },
];

export const occupation = [
  { code: 'whao_Q6A_ScE', name: 'Sanering & Renhållning' },
  { code: 'ScKy_FHB_7wT', name: 'Hotell, restaurang, storhushåll' },
  { code: 'j7Cq_ZJe_GkT', name: 'Bygg & Anläggning' },
  { code: 'kJeN_wmw_9wX', name: 'Naturvetenskap' },
  { code: 'Uuf1_GMh_Uvw', name: 'Kropps- & Skönhetsvård' },
  { code: 'E7hm_BLq_fqZ', name: 'Säkerhet & Bevakning' },
  { code: 'bh3H_Y3h_5eD', name: 'Chefer & Verksamhetsledare' },
  { code: '9puE_nYg_crq', name: 'Kultur, Media & Design' },
  { code: 'VuuL_7CH_adj', name: 'Naturbruk' },
  { code: 'PaxQ_o1G_wWH', name: 'Hantverk' },
  { code: 'NYW6_mP6_vwf', name: 'Hälso- & Sjukvård' },
  { code: 'wTEr_CBC_bqh', name: 'Industriell tillverkning' },
  { code: 'MVqp_eS8_kDZ', name: 'Pedagogik' },
  { code: 'bH5L_uXD_ZAX', name: 'Militära yrken' },
  { code: 'yhCP_AqT_tns', name: 'Installation, drift & underhåll' },
  { code: 'RPTn_bxG_ExZ', name: 'Försäljning, inköp, marknadsföring' },
  { code: 'apaJ_2ja_LuF', name: 'Data & IT' },
  { code: 'ASGV_zcE_bWf', name: 'Transport, distribution & lager' },
  { code: 'GazW_2TU_kJw', name: 'Yrken med social inriktning' },
  { code: '6Hq3_tKo_V57', name: 'Yrken med teknisk inriktning' },
  { code: 'X82t_awd_Qyc', name: 'Administration, ekonomi & juridik' },
];
 